name: Report Bundle Size
on: pull_request

jobs:
  report-bundle-size:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JS_APP_DIRECTORY: ${{ github.workspace }}
      BASE_REPORT_PRESERVE_DIRECTORY: ~/${{ github.sha }}-report
      BASE_REPORT_FILENAME: base-report.json

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"

    - name: Checkout base branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}

    - name: Cache base branch yarn.lock
      uses: actions/cache@v2
      id: yarn-cache-base
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

    - name: Install packages to base branch
      working-directory: ${{ env.JS_APP_DIRECTORY }}
      run: |
        yarn install --frozen-lockfile

    - name: Generate base branch bundle report
      working-directory: ${{ env.JS_APP_DIRECTORY }}
      run: |
        yarn analyze:ci

    - name: Preserve report for base branch
      id: preserve-report
      run: |
        mkdir ${{ env.BASE_REPORT_PRESERVE_DIRECTORY }}
        mv report.json ${{ env.BASE_REPORT_PRESERVE_DIRECTORY }}/${{ env.BASE_REPORT_FILENAME }}

    - name: Checkout compare branch
      uses: actions/checkout@v2

    - name: Cache compare branch yarn.lock
      uses: actions/cache@v2
      id: yarn-cache-compare
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

    - name: Install packages to compare branch
      working-directory: ${{ env.JS_APP_DIRECTORY }}
      run: |
        yarn install --frozen-lockfile

    - name: Generate compare bundle report
      working-directory: ${{ env.JS_APP_DIRECTORY }}
      run: |
        yarn analyze:ci

    - name: Recover report from base branch
      working-directory: ${{ env.JS_APP_DIRECTORY }}
      run: |
        mv ${{ env.BASE_REPORT_PRESERVE_DIRECTORY }}/${{ env.BASE_REPORT_FILENAME }} .

    - name: Create PR comment
      working-directory: ${{ env.JS_APP_DIRECTORY }}
      run: |
        yarn danger ci --dangerfile ./scripts/report-bundle-size.ts --dangerId bundle_size
