name: Report Test Coverage
on: pull_request

jobs:
  report-test-coverage:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - uses: actions/checkout@v2

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache yarn.lock
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

    - name: Install packages
      run: |
        yarn install --frozen-lockfile

    - name: Generate coverage report
      run: |
        yarn test:ci:coverage

    - name: Create PR comment
      run: |
        yarn danger ci --dangerfile ./scripts/report-test-coverage.ts --dangerId test_coverage
