name: Report Code Coverage
on: pull_request

jobs:
  report-code-coverage:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node_modules
      uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

    - name: Install packages
      run: |
        yarn install --frozen-lockfile

    - name: Generate coverage report
      run: |
        yarn test:ci

    - name: Create PR comment
      run: |
        yarn danger ci --dangerfile ./scripts/report-code-coverage.ts
