name: Report Bundle Size
on: pull_request

jobs:
  report-bundle-size:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    env:
      BASE_DIR_NAME: base
      COMPARE_DIR_NAME: compare
      BASE_DIR: ${{ GITHUB_WORKSPACE }}/base
      COMPARE_DIR: ${{ GITHUB_WORKSPACE }}/compare

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout base branch
    - uses: actions/checkout@v2
      with:
        ref: master
        path: ${{ BASE_DIR_NAME }}
    
    - name: Checkout compare branch
    - uses: actions/checkout@v2
      with:
        path: ${{ COMPARE_DIR_NAME }}

    - name: Install packages to base branch
      working-directory: ${{ BASE_DIR }}
      run: |
        yarn install --frozen-lockfile

    - name: Generate base bundle report
      working-directory: ${{ BASE_DIR }}
      run: |
        yarn analyze:ci

    - name: Move base report to compare
      working-directory: ${{ BASE_DIR }}
      run: |
        cp report.json $COMPARE_DIR/base-report.json

    - name: Install packages to compare branch
      working-directory: ${{ COMPARE_DIR }}
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: |
        yarn install --frozen-lockfile

    - name: Generate compare bundle report
      working-directory: ${{ COMPARE_DIR }}
      run: |
        yarn analyze:ci

    - name: Create PR comment
      run: |
        yarn danger ci
