name: Report Bundle Size
on: pull_request

jobs:
  report-bundle-size:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"

    - name: Checkout base branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}

    - name: Cache base branch yarn.lock
      uses: actions/cache@v1
      id: yarn-cache-base
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-base-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-base-

    - name: Optionally install packages to base branch
      if: steps.yarn-cache-base.outputs.cache-hit != 'true'
      run: |
        yarn install --frozen-lockfile

    - name: Generate base branch bundle report
      run: |
        yarn analyze:ci

    - name: Preserve report for base branch
      run: |
        mv report.json ../base-report.json

    - name: Checkout compare branch
      uses: actions/checkout@v2

    - name: Cache compare branch yarn.lock
      uses: actions/cache@v1
      id: yarn-cache-compare
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-compare-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-compare-

    - name: Optionally install packages to compare branch
      if: steps.yarn-cache-compare.outputs.cache-hit != 'true'
      run: |
        yarn install --frozen-lockfile

    - name: Generate compare bundle report
      run: |
        yarn analyze:ci

    - name: Recover report from base branch
      run: |
        mv ../base-report.json base-report.json

    - name: Create PR comment
      run: |
        yarn danger ci
